In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy
import seaborn as sns
import statsmodels.api as sm

# Event Studies

In [21]:
t   = np.arange(1000)
t0  = 500
t

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [22]:
2 * (t < t0)
# (t < t0)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [23]:
1 * (t >= t0)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

The above creates a rectangular pulse or step function that "turns off" at t=500. It's commonly used in signal processing, control systems, or mathematical modeling where you want to represent something that changes abruptly at a specific point in time.

This code below is implementing a **regression discontinuity design** or **interrupted time series analysis** to detect a structural break/change in a time series at t=500.

**Creating the outcome variable Y:**
```python
Y = (2 * (t < t0)) + (1 * (t >= t0)) + np.random.normal(0, 1, (1000,))
```
- Before t=500: Y = 2 + noise
- After t=500: Y = 1 + noise  
- So there's a level drop from 2 to 1 at the breakpoint, plus random noise

**Creating the regression variables:**
- `After = 1 * (t >= t0)`: Dummy variable (0 before t=500, 1 after)
- `t_After = (t - t0) * After`: Interaction term that's 0 before t=500, then counts up from 0 after t=500
- `t`: Linear time trend

**The regression model being estimated:**
```
Y = β₀ + β₁*After + β₂*t + β₃*t_After + ε
```

Where:
- **β₀** (intercept): baseline level before the break
- **β₁** (After): immediate level change at t=500 
- **β₂** (t): slope/trend before the break
- **β₃** (t_After): change in slope after the break

**What the t-values tell you:**
- `results.tvalues` shows which effects are statistically significant
- You'd expect β₁ to be significantly negative (≈ -1) since there's a drop from 2 to 1
- β₂ and β₃ should be near 0 since there are no trends in the simulated data, just a level shift

This is a common econometric technique for analyzing policy interventions, treatment effects, or any situation where you want to test if something changed at a specific point in time.


In [24]:
Y       = (2 * (t < t0)) + (1 * (t >= t0)) + np.random.normal(0, 1, (1000,))

After   = 1 * (t >= t0)
t_After = (t - t0) * After
# intercept (before), After, before trend (t), after trend (t - t0) * After

X = sm.add_constant(pd.DataFrame(
    {
        "After": After, 
        "t_After": t_After, 
        "t": t
    }
))
results = sm.OLS(Y, X).fit()
results.tvalues

const      21.771443
After      -8.225310
t_After    -1.509277
t           1.313783
dtype: float64

In [25]:
# Scenario: after a new grocery store opens up, does our (old) store reduce the price of a pound of apples?
# First experiment: yes, it reduces
t   = np.arange(1000)
t0  = 500
Y   = (2 * (t < t0)) + (1 * (t >= t0)) + np.random.normal(0, 1, (1000,))
# Test
After   = 1 * (t >= 500)
t_After = (t - t0) * After
X = sm.add_constant(pd.DataFrame(
    {
        "After": After,
        "t_After": t_After,
        "t": t
    }
))
results = sm.OLS(Y, X).fit()
results.params

const      1.979117
After     -0.917284
t_After    0.000353
t         -0.000147
dtype: float64

In [26]:
results.tvalues

const      21.843849
After      -7.148154
t_After     0.793061
t          -0.466834
dtype: float64


**What the function is designed to do:**
This creates a more flexible event study where you can specify:
- `before_const`: baseline level before the break
- `after_const`: level shift at the break  
- `before_slope`: trend before the break
- `after_slope`: trend after the break
- The break point is at the midpoint (`t0 = num_times/2`)

**Your example parameters:**
- Before break: Y = 2.0 + 0.01*t + noise (level 2, slight upward trend)
- After break: Y = 1.0 + 0*t + noise (level 1, no trend)
- So there's both a level drop (-1) and a slope change (-0.01)

Once fixed, `results.bse` will show the standard errors of the regression coefficients, helping you assess the precision of your estimates of the structural break effects.

In [30]:
def event_study(num_times, before_const, after_const, before_slope, after_slope, sigma):
    t       = np.arange(num_times)
    t0      = int(num_times / 2)
    Y       = (
                before_const * (t < t0) + 
                before_slope * t + 
                after_const * (t >= t0) + 
                (after_slope - before_slope) * (t - t0) * (t >= t0) + 
                np.random.normal(0, sigma, (num_times,))
               )
    # Test
    After   = 1 * (t >= t0)
    t_After = (t - t0) * After
    X       = sm.add_constant(pd.DataFrame(
        {
            "After": After, 
            "t_After": t_After, "t": t
            }
        ))
    results = sm.OLS(Y, X).fit()
    return results

In [37]:

results     = event_study(num_times = 1000000, before_const = 2.0, after_const = 1.0, before_slope = 0.01, after_slope = 0, sigma = 1)
results.bse # standard errors of the regression coefficients

const      2.826403e-03
After      3.997143e-03
t_After    1.384651e-08
t          9.790962e-09
dtype: float64

In [33]:
results = event_study(num_times = 100000, before_const = 2.0, after_const = 1.9, before_slope = 0, after_slope = 0, sigma = 1)
results.params

const      2.013791e+00
After     -1.075786e-01
t_After    4.168109e-07
t         -2.202220e-07
dtype: float64

In [34]:
results.tvalues

const      225.847346
After       -8.531101
t_After      0.954174
t           -0.712958
dtype: float64

In [35]:
results = event_study(num_times = 1000, before_const = 2.0, after_const = 1.9, before_slope = 0, after_slope = 1, sigma = 1)
results.params

const      2.183851
After     -0.103131
t_After    1.001072
t         -0.000615
dtype: float64

# Differences-in-differences

In [ ]:
# Scenario: a new grocery store opens up in town A but not town B.  Do the stores in town A reduce the price of a pound of apples
# because of this event?  Or do they reduce it for other reasons?

# First experiment: yes, it reduces
t       = np.arange(1000)
t0      = 500
Y_A     = 2 * (t < t0) + 1 * (t >= t0) + np.random.normal(0, 1, (1000,))
Y_B     = 1.5 + np.random.normal(0, 1, (1000,))
Y       = np.concatenate((Y_A, Y_B))
group_A = np.concatenate((np.ones(1000), np.zeros(1000)))
After   = np.tile(1 * (t >= t0), 2)
Treated = group_A * After
X       = sm.add_constant(pd.DataFrame({"alpha_group": group_A, "alpha_time": After, "beta_1": Treated}))
results = sm.OLS(Y, X).fit()
results.params

const          1.563259
alpha_group    0.446071
alpha_time    -0.114006
beta_1        -0.962349
dtype: float64

In [ ]:
def DID(num_times, before_const_A, after_const_A, before_const_B, after_const_B, sigma):
    t       = np.arange(num_times)
    t0      = int(num_times / 2)
    Y_A     = before_const_A * (t < t0) + after_const_A * (t >= t0) + np.random.normal(0, sigma, (num_times,))
    Y_B     = before_const_B * (t < t0) + after_const_B * (t >= t0) + np.random.normal(0, sigma, (num_times,))
    Y       = np.hstack((Y_A, Y_B))
    group_A = np.hstack((np.ones(num_times), np.zeros(num_times)))
    After   = np.hstack((1 * (t >= t0), 1 * (t >= t0)))
    X       = sm.add_constant(pd.DataFrame({"alpha_group": group_A, "alpha_time": After, "beta_1": group_A * After}))
    results = sm.OLS(Y, X).fit()
    return results

results = DID(num_times = 1000, before_const_A = 1.0, after_const_A = 2.0, before_const_B = 2.0, after_const_B = 3.0, sigma = 1)
results.params

const          2.033343
alpha_group   -1.044050
alpha_time     1.023215
beta_1         0.067328
dtype: float64

In [ ]:
results.tvalues

const          47.001515
alpha_group   -17.065053
alpha_time     16.724505
beta_1          0.778151
dtype: float64

In [ ]:
results = DID(num_times = 1000, before_const_A = 1.0, after_const_A = 3.0, before_const_B = 2.0, after_const_B = 3.0, sigma = 1)
results.params

const          1.924710
alpha_group   -0.915991
alpha_time     1.040818
beta_1         0.983208
dtype: float64